architecture:
  type: TSViT
  params:
    num_classes: 2
    image_size: 224 #1536
    patch_size: 56 #512
    dim: 516
    depth: 6
    heads: 12
    mlp_dim: 1024
    dropout: 0.1
    emb_dropout: 0.1
    num_frames: 16

