dataset:
  train:
    #path: /workspace/dataset/grid_data/train
    path: /workspace/dataset/server_data5_fps2/train
    batch_size: 16
    shuffle: True
    drop_last: True
    preprocess:
      - type: horizontal


  test:
    path : /workspace/dataset/server_data5_fps2/test
    batch_size: 8
