dataset:
  train:
    path: /workspace/raw_data/UBI_FIGHTS/UBI_FIGHTS/UBI_CLIP_DATASET2/train
    batch_size: 8
    shuffle: True
    #drop_last: True
    #preprocess:
    #  - type: horizontal


  test:
    path : /workspace/raw_data/UBI_FIGHTS/UBI_FIGHTS/UBI_CLIP_DATASET2/test
    batch_size: 16
    shuffle: False
